agriculture/urls.py
from django.urls import path
from agriculture.views import *


app_name = 'agriculture'

urlpatterns = [
    path('', agriculture_home, name="agriculture_home"),
    # path('admin/', admin_view, name="admin_view"),
    path('delete/<int:pk>/', delete, name='delete'),
    path('json/', show_json, name='show_json'),
    path('add/', add_item, name='add_task'),
    path('single/<int:pk>/', single_view, name='single_view'),
    path('add-flutter/', add_flutter, name='add_flutter'),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home')
]

tugas_tengah_semester/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("authentication/", include("authentication.urls")),
    path("tender/", include("tender.urls")),
    path("healthcare/", include("Healthcare.urls")),
    path("marine/", include("marine.urls")),
    path("tourism/", include("tourism.urls")),
    path("waste/", include("waste.urls")),
    path("agriculture/", include("agriculture.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agriculture/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Items(models.Model):
    photo_url = models.TextField(null=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.BigIntegerField()
    contact_name = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=255)

agriculture/forms.py
from dataclasses import field
from django.forms import ModelForm
from agriculture.models import Items
from django import forms

class AdminForm(ModelForm):
    class Meta:
        model = Items
        fields = ["title", "description", "photo_url", "price", "contact_name", "contact_number"]

agriculture/views.py
from multiprocessing import context
from django.shortcuts import *
from agriculture.models import *
from django.contrib import messages
from django.core import serializers
from .forms import *
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.db.models.fields.files import ImageFieldFile
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json
# Create your views here.

#request.user.is_authenticated
#request.user.is_superuser
@login_required(login_url='/authentication/login/')
def agriculture_home(request):
    data = Items.objects.all()
    if request.user.is_authenticated and request.user.is_superuser:
        data = Items.objects.all()
        form = AdminForm()
        if request.method == "POST":
            form = AdminForm(request.POST, request.FILES )
            if form.is_valid():
                form.save()
        # for item in data:
        #     if item:
        #         item.delete()
        context = {
            'last_login': request.COOKIES.get('last_login'),
            'items_data': data,
            'form': form,
            'user': request.user,
        }
        return render(request, "admin2_view.html", context)
        

    context = {
        'last_login': request.COOKIES.get('last_login'),
        'items_data': data,
        'user': request.user,
    }
    return render(request, "agriculture_home.html", context)

def delete(request, pk):
    item = Items.objects.get(id=pk)
    if item:
        item.delete()
        return redirect('agriculture:agriculture_home')
        
    messages.error(request, 'Error! Tidak dapat menghapus task')
    return redirect('agriculture:agriculture_home')

def show_json(request):
    data = Items.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def add_item(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        photo_url = request.POST.get('photo_url')
        title = request.POST.get('title')
        description = request.POST.get('description')
        price = request.POST.get('price')
        contact_name = request.POST.get('contact_name')
        contact_number = request.POST.get('contact_number')
        item = Items.objects.create(photo_url=photo_url, title=title, description=description, price=price, contact_name=contact_name, contact_number=contact_number)
        result = {
            'pk':item.pk,
            'fields':{
                'photo_url':item.photo_url,
                'title':item.title,
                'description':item.description,
                'price': item.price,
                'contact_name': item.contact_name,
                'contact_number': item.contact_number,
            }
        }
        return JsonResponse(result)    
    return HttpResponseBadRequest()

def single_view(request, pk):
    data = Items.objects.get(id= pk)
    context = {
        'last_login': request.COOKIES.get('last_login'),
        'item': data,
        'user': request.user,
    }
    return render(request, "single_view.html", context)

@csrf_exempt
def add_flutter(request):
    if request.method == 'POST':
        # Items.objects.all().delete()
        data = json.loads(request.body)
        title = data["title"]
        description = data["description"]
        contact_name = data["contact_name"]
        contact_number = data["contact_number"]
        price = data["price"]
        photo_url = data["photo_url"]
        addItem = Items.objects.create(
            title = title, 
            description = description,
            contact_name = contact_name,
            contact_number = contact_number, 
            price = price, 
            photo_url = photo_url, 
        )
        addItem.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

agriculture/templates/admin2_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{%static 'js/admin2.js' %}" defer></script>
  
<div class="bg-white">
  <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
    <h2 class="sr-only">Items</h2>
    <form action="" class="w-full" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
            Crops name
          </label>
          {{form.title}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"> -->
        </div>
        <div class="w-full md:w-1/2 px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
            Price
          </label>
          {{form.price}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"> -->
        </div>
      </div>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
            Contact name
          </label>
          {{form.contact_name}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"> -->
        </div>
        <div class="w-full md:w-1/2 px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
            Contact number
          </label>
          {{form.contact_number}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"> -->
        </div>
      </div>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
            Description
          </label>
          {{form.description}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"> -->
        </div>
        <div class="w-full md:w-1/2 px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
            Photo URL
          </label>
          {{form.photo_url}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"> -->
        </div>
      </div>
      <button type="submit" class="mt-4 bg-emerald-400 px-4 py-2 rounded-lg shadow-md text-white hover:bg-emerald-600 duration-300">
        + Add item
      </button>
    </form>
      <!-- <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Fish name</label>
            {{form.title}}
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Price</label>
            {{form.price}}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Contact name</label>
            {{form.contact_name}}
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Contact number</label>
            {{form.contact_number}}
          </div>
        </div>
        <div class="form-group">
          <label for="inputAddress2">Description</label>
          {{form.description}}
        </div>
        <div class="form-group">
          <label for="inputAddress2">Photo</label>
          {{form.photo}}
        </div>
        <input type="submit" id="add-item">
      </form> -->
    

    <div id="items" class="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">

      <!-- More products... -->
    </div>
  </div>
</div>


{% endblock content %}

agriculture/templates/admin_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{%static 'js/admin.js' %}" defer></script>
  
<div class="bg-white">
  <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
    <h2 class="sr-only">Items</h2>
    <form action="" class="w-full" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
            Corps name
          </label>
          {{form.title}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"> -->
        </div>
        <div class="w-full md:w-1/2 px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
            Price
          </label>
          {{form.price}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"> -->
        </div>
      </div>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
            Contact name
          </label>
          {{form.contact_name}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"> -->
        </div>
        <div class="w-full md:w-1/2 px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
            Contact number
          </label>
          {{form.contact_number}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"> -->
        </div>
      </div>
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
            Description
          </label>
          {{form.description}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"> -->
        </div>
        <div class="w-full md:w-1/2 px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
            Photo
          </label>
          {{form.photo_url}}
          <!-- <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"> -->
        </div>
      </div>
      <button type="submit" class="mt-4 bg-emerald-400 px-4 py-2 rounded-lg shadow-md text-white hover:bg-emerald-600 duration-300">
        + Add item
      </button>
    </form>
      <!-- <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Fish name</label>
            {{form.title}}
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Price</label>
            {{form.price}}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Contact name</label>
            {{form.contact_name}}
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Contact number</label>
            {{form.contact_number}}
          </div>
        </div>
        <div class="form-group">
          <label for="inputAddress2">Description</label>
          {{form.description}}
        </div>
        <div class="form-group">
          <label for="inputAddress2">Photo</label>
          {{form.photo}}
        </div>
        <input type="submit" id="add-item">
      </form> -->
    

    <div id="items" class="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">

      <!-- More products... -->
    </div>
  </div>
</div>


{% endblock content %}

agriculture/templates/agriculture_home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{%static 'js/user2.js' %}" defer></script>

<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/aspect-ratio'),
    ],
  }
  ```
-->

<div class="bg-white">
    <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
      <h2 class="sr-only">Products</h2>
  
      <div id="items" class="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
        
        
  
        <!-- More products... -->
      </div>
    </div>
  </div>

  
{% endblock content %}

agriculture/templates/single_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font overflow-hidden bg-white">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <img alt="ecommerce" class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="{{item.photo_url}}">
        <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">CROPS NAME</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{item.title}}</h1>
          <p class="leading-relaxed">{{item.description}}</p>
          <p>Contact name: {{item.contact_name}}</p>
          <p>Contact number: {{item.contact_number}}</p>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">Rp{{item.price}}</span>
          </div>
          {% if user.is_superuser %}
          <button class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded"><a href="{% url 'agriculture:delete' item.pk %}">Delete item</a></button>
          {% endif %}
        </div>
      </div>
    </div>
  </section>


{% endblock content %}