home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home')
]

tourism/urls.py
from django.urls import path
from tourism.views import *

app_name = 'tourism'

urlpatterns = [
    path('', show_tourism, name='show_tourism'),
    path('add/', add_tourism, name='add_tourism'),
    path('add_visitor/<int:id>', add_visitor, name='add_visitor'),
    path('delete/', delete_tourism, name='delete_tourism'),
    path('add_visitor_flutter/<int:id>', add_visitor_flutter, name='add_visitor_flutter'),
    path('json', get_tourism_json, name='get_tourism_json'),
    path('add_flutter/', add_tourism_flutter, name='add_tourism_flutter'),
    path('adminCheck',admin_check_api,name='admin_check_api'),
]

tugas_tengah_semester/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("authentication/", include("authentication.urls")),
    path("tender/", include("tender.urls")),
    path("healthcare/", include("Healthcare.urls")),
    path("marine/", include("marine.urls")),
    path("tourism/", include("tourism.urls")),
    path("waste/", include("waste.urls")),
    path("agriculture/", include("agriculture.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourism/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Place(models.Model):
    name = models.TextField(max_length=100)
    description = models.TextField(max_length=200)
    price = models.PositiveIntegerField(default=0)
    image = models.CharField(max_length=200)
    visitor = models.PositiveIntegerField(default=0)

tourism/forms.py
from django.forms import ModelForm
from .models import Place

class PlaceForm(ModelForm):
    class Meta:
        model = Place
        fields = ['image','name','description','price']

tourism/views.py
from django.shortcuts import redirect, render
from .forms import PlaceForm
from .models import Place
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import  HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='/authentication/login/')
def show_tourism(request):
    place = Place.objects.all()
    context = {
        'last_login': request.COOKIES.get('last_login'),
        'place': place,
        'form': PlaceForm(),
    }
    return render(request, "tourism.html", context)


@login_required(login_url='/authentication/login/')
def add_tourism(request):
    if request.user.is_superuser:
        if request.method == 'POST':
                form = PlaceForm(request.POST, request.FILES)
                print(form.is_valid())
                if form.is_valid():
                    name = form.cleaned_data['name']
                    description = form.cleaned_data['description']
                    price = form.cleaned_data['price']
                    image = form.cleaned_data['image']
                    place = Place(price=price, name=name,
                                description=description, image=image)
                    place.save()
                    return redirect('tourism:show_tourism')
        else:
            form = PlaceForm()

        context = {
        'last_login': request.COOKIES.get('last_login'),
        'form': PlaceForm(),
        }
        return render(request, 'create.html', context)
    HttpResponseNotFound

# @login_required(login_url='/authentication/login/')
def get_tourism_json(request):
    place = Place.objects.all()
    return HttpResponse(serializers.serialize('json', place), content_type='application/json')

@login_required(login_url='/authentication/login/')
def add_visitor(request, id):
    response = {}
    if request.method == 'GET':
        place = Place.objects.get(pk=id)
        place.visitor = place.visitor + 1
        place.save()
        response['visitor'] = place.visitor
        return JsonResponse(response)
        
@csrf_exempt
def add_visitor_flutter(request, id):
    response = {}
    if request.method == 'GET':
        place = Place.objects.get(pk=id)
        place.visitor = place.visitor + 1
        place.save()
        response['visitor'] = place.visitor
        return JsonResponse({
            'status': True,
            'message': 'Visitor Berhasil ditambahkan!',
        }, status=200)
       
@csrf_exempt
def delete_tourism(request):
     Place.objects.all().delete()
     return JsonResponse({
            'status': True,
            'message': 'Place Berhasil dihapus!',
        }, status=200)

@csrf_exempt
def add_tourism_flutter(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        price = request.POST.get("price")
        image = request.POST.get("image")
        place = Place(price=price, name=name,
                                description=description, image=image)
        place.save()
        return JsonResponse({
            'status': True,
            'message': 'Data Berhasil ditambahkan!',
        }, status=200)   

def admin_check_api(request):
    def get():
        if request.user.is_authenticated:
            if request.user.is_superuser:
                return JsonResponse({'status': 201, 'message': 'Admin'}, status=201)
            return JsonResponse({'status': 402, 'message': 'You are not admin'}, status=402)
        return JsonResponse({'status': 401, 'message': 'You must be logged in'}, status=401)
    if (request.method == 'GET'): return get()             

tourism/templates/create.html
{% extends 'base.html' %} {% load static %} 
{% block meta %}
{% endblock meta %} {% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <button id="button" type=“submit”>Enter</button>
</form>


<script>
    function create() {
        fetch("{% url 'tourism:add_tourism' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        })
        return false
    }
    document.getElementById("button").onclick = create
</script>
{% endblock content %}

tourism/templates/tourism.html
{% extends 'base.html' %}

{% block content %}

<div class="flex justify-center">
<div>
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

<script>
  function addTicket(id) {
    $.ajax({
      url: `./add_visitor/${id}`,
      datatype: `json`,
      success: function(data) {
        $(`#visitor${id}`).html(`total visitor : ${data.visitor}`);
      },
    });
  }
</script>
  {% for place in place %}
  <br />
  <div class="max-w-sm rounded overflow-hidden shadow-lg">
    <img class="w-full" src="{{place.image}}" alt="Sunset in the mountains">
    <div class="px-6 py-4">
      <div class="font-bold text-xl mb-2">{{place.name}}</div>
      <p class="text-gray-700 text-base">
        {{place.description}}
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <span style="background-color: rgb(171, 214, 171);" class="inline-block rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Price : Rp.{{place.price}},00
      </span>
      <span id="visitor{{place.id}}" style="background-color: rgb(148, 148, 193);" class="inline-block rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">total visitor : {{place.visitor}}
      </span>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><a onclick="addTicket('{{place.id}}');" href="#" >+ buy ticket</a>
      </span>
      
    </div>
  </div>
  {% endfor %}
</div>
</div>



{% endblock content %}